
name: Update Website

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  update-website:
    runs-on: ubuntu-latest
    steps:
      - name: get node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: checkout mstream.io source code
        uses: actions/checkout@v6
        with:
          path: website
          repository: IrosTheBeggar/mstream-website
          ref: master
          ssh-private-key: ${{ secrets.WEBSITE_KEY }}
      - name: checkout mStream app code
        uses: actions/checkout@v6
        with:
          path: mstream
          repository: IrosTheBeggar/mStream
          ref: master
      - run: ls
      - run: |
          cd website
          VERS=$(node -pe "require('../mstream/package.json').version")
          node -pe "require('../mstream/package.json').version"
          echo "v$(node -pe "require('../mstream/package.json').version")" 
          echo $VERS
          sed -i "s/[1-9]\+[0-9]*\.[0-9]\+\.[0-9]\+/$VERS/g" templates/express.html
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "action: update server"
          git push


